In [26]:
from tensorflow.keras.preprocessing.text import one_hot

In [27]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [28]:
voc_size = 10000

In [29]:
ohe = [one_hot(words,voc_size)for words in sent]
ohe

[[6859, 8692, 7061, 6759],
 [6859, 8692, 7061, 9647],
 [6859, 5934, 7061, 3569],
 [9427, 6058, 3719, 1563, 9397],
 [9427, 6058, 3719, 1563, 2393],
 [7208, 6859, 5339, 7061, 2425],
 [788, 8491, 8478, 1563]]

In [30]:
from tensorflow.keras.layers import Embedding
#from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [31]:
import numpy as np

In [38]:
#pad_sequencing
sent_length = 8
embedded_docs = pad_sequences(ohe,padding = 'pre',maxlen = sent_length )
print(embedded_docs)


[[   0    0    0    0 6859 8692 7061 6759]
 [   0    0    0    0 6859 8692 7061 9647]
 [   0    0    0    0 6859 5934 7061 3569]
 [   0    0    0 9427 6058 3719 1563 9397]
 [   0    0    0 9427 6058 3719 1563 2393]
 [   0    0    0 7208 6859 5339 7061 2425]
 [   0    0    0    0  788 8491 8478 1563]]


In [33]:
#feature reporesentation

dim = 10

In [36]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [40]:
model.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_4 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [39]:
model.build(input_shape=(None, sent_length))
model.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_4 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [41]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 124ms/step


array([[[-3.70996818e-02,  4.41846959e-02, -1.64715871e-02,
         -1.65902600e-02, -4.58150618e-02,  2.06586979e-02,
          2.67556943e-02, -1.19997375e-02, -2.18027476e-02,
          3.58323567e-02],
        [-3.70996818e-02,  4.41846959e-02, -1.64715871e-02,
         -1.65902600e-02, -4.58150618e-02,  2.06586979e-02,
          2.67556943e-02, -1.19997375e-02, -2.18027476e-02,
          3.58323567e-02],
        [-3.70996818e-02,  4.41846959e-02, -1.64715871e-02,
         -1.65902600e-02, -4.58150618e-02,  2.06586979e-02,
          2.67556943e-02, -1.19997375e-02, -2.18027476e-02,
          3.58323567e-02],
        [-3.70996818e-02,  4.41846959e-02, -1.64715871e-02,
         -1.65902600e-02, -4.58150618e-02,  2.06586979e-02,
          2.67556943e-02, -1.19997375e-02, -2.18027476e-02,
          3.58323567e-02],
        [ 3.34218778e-02, -1.76781528e-02,  2.19999216e-02,
         -2.72151083e-03,  4.12365682e-02,  5.77583164e-03,
          2.34466456e-02,  4.90982272e-02, -1.008336

In [43]:
embedded_docs[0]

array([   0,    0,    0,    0, 6859, 8692, 7061, 6759], dtype=int32)

In [46]:
model.predict(embedded_docs[[0]])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 149ms/step


array([[[-0.03709968,  0.0441847 , -0.01647159, -0.01659026,
         -0.04581506,  0.0206587 ,  0.02675569, -0.01199974,
         -0.02180275,  0.03583236],
        [-0.03709968,  0.0441847 , -0.01647159, -0.01659026,
         -0.04581506,  0.0206587 ,  0.02675569, -0.01199974,
         -0.02180275,  0.03583236],
        [-0.03709968,  0.0441847 , -0.01647159, -0.01659026,
         -0.04581506,  0.0206587 ,  0.02675569, -0.01199974,
         -0.02180275,  0.03583236],
        [-0.03709968,  0.0441847 , -0.01647159, -0.01659026,
         -0.04581506,  0.0206587 ,  0.02675569, -0.01199974,
         -0.02180275,  0.03583236],
        [ 0.03342188, -0.01767815,  0.02199992, -0.00272151,
          0.04123657,  0.00577583,  0.02344665,  0.04909823,
         -0.01008337, -0.01487467],
        [-0.00728744, -0.01373493, -0.03044297, -0.02410552,
          0.01728434, -0.01158752, -0.02335287, -0.01752213,
          0.03063473,  0.03810338],
        [-0.01575211,  0.0382699 , -0.02796556,  0.0